/**
 * Generate public/sitemap.xml and public/robots.txt from the route registry.
 *
 * Generated rather than hand-maintained for one reason: a sitemap that lists
 * a URL which 404s, or omits a URL that exists, is a silent failure. Nothing
 * breaks, nothing logs, and you find out weeks later in Search Console. The
 * only reliable fix is to derive the file from the same array the router uses.
 *
 * Runs in `prebuild`, so `npm run build` can never ship a stale sitemap.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/* Imported straight from source. These modules are plain data with no browser
   dependencies, which is what lets a build script read them. */
import { ROUTES } from '../src/lib/routes.js';
import { SITE, url } from '../src/lib/site.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.resolve(__dirname, '..', 'public');

/** YYYY-MM-DD in UTC. */
const today = new Date().toISOString().slice(0, 10);

function sitemap() {
    const entries = ROUTES.map((route) => {
        const lines = [
            `    <loc>${url(route.path)}</loc>`,
            `    <lastmod>${route.lastmod || today}</lastmod>`,
        ];
        if (route.changefreq) lines.push(`    <changefreq>${route.changefreq}</changefreq>`);
        if (route.priority != null) {
            lines.push(`    <priority>${route.priority.toFixed(1)}</priority>`);
        }
        return `  <url>\n${lines.join('\n')}\n  </url>`;
    });

    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- GENERATED by scripts/generate-sitemap.mjs — do not edit by hand. -->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        ...entries,
        '</urlset>',
        '',
    ].join('\n');
}

function robots() {
    return [
        '# GENERATED by scripts/generate-sitemap.mjs — do not edit by hand.',
        `# ${SITE.origin}`,
        'User-agent: *',
        'Allow: /',
        '',
        `Sitemap: ${url('/sitemap.xml')}`,
        '',
    ].join('\n');
}

async function main() {
    await mkdir(publicDir, { recursive: true });

    await writeFile(path.join(publicDir, 'sitemap.xml'), sitemap(), 'utf8');
    await writeFile(path.join(publicDir, 'robots.txt'), robots(), 'utf8');

    console.log(`sitemap.xml — ${ROUTES.length} URLs`);
    console.log('robots.txt  — written');
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
